name: pipeline_letting


# 'on' and 'push' indicate that the pipeline is triggered when a push is made.
# With pull requests we specify that we only target the main branch.
on:
  push:
  pull_request:
    branch:
      - main


# Declares environment variables.
env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DSN: ${{ secrets.DSN }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
  RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}


# Tasks that the pipeline must execute.
# 'ubuntu-latest' is the operating system used.
# 'uses' specifies the GitHub Action version and the Python version used.
# 'create .env file' is used here to create environment variables.
# 'run' is used to install flake8, setuptools and requirements.txt.
# 'run flake8' to execute flake8.
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: create .env file
        run: |
            echo SECRET_KEY=$SECRET_KEY >> .env
            echo DSN=$DSN >> .env
      - run: pip install flake8
      - run: pip install setuptools>=65.5.1 wheel>=0.38.1
      - run: pip install -r requirements.txt
      - run: flake8 .

# We specify 'needs', meaning that this job waits for another one to finish before running.
# Executes the commands for test coverage.
  test-and-coverage:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: create .env file
        run: |
            echo SECRET_KEY=$SECRET_KEY >> .env
            echo DSN=$DSN >> .env
      - run: pip install setuptools>=65.5.1 wheel>=0.38.1
      - run: pip install -r requirements.txt
      - run: coverage erase
      - run: coverage run manage.py test
      - run: coverage report

# Here we reuse the same setup as above, but change the 'needs'.
# The 'if' condition specifies that the job only runs on the main branch.
# With 'docker login' we authenticate to Docker,we specify that we use Docker's registry.
# The other Docker commands retrieve information from Docker Hub, build an image,
# and push everything back to Docker Hub.
# We build two images: the one with the 'SHA' tag is unique each time, the one the 'latest' tag is overwritten.
# We push a single image with both tags.
  build-and-push:
    runs-on: ubuntu-latest
    needs: test-and-coverage
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: create .env file
        run: |
            echo SECRET_KEY=$SECRET_KEY >> .env
            echo DSN=$DSN >> .env
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY
      # - run: docker pull $DOCKER_USERNAME/$DOCKER_IMAGE
      - run: docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE:$GITHUB_SHA -t $DOCKER_USERNAME/$DOCKER_IMAGE:latest .
      - run: docker push --all-tags $DOCKER_USERNAME/$DOCKER_IMAGE

# Render is enabled here.
  deploy-to-render:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: execute render hook
        run: |
          curl -X GET $RENDER_DEPLOY_HOOK
